name: Hello World!

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
      - name: Print date
        run: |
          echo date
      - name: Print directory
        run: |
          echo ls -l